const Plants = [
  {
    name: "Bird of paradice",
    price: 450,
    summary: "Perfect easy care plant",
    image: "/products/birds.png",
    tags: ["indoor/outdoor"],
  },
  {
    name: "Rubber Tree",
    price: 750,
    summary: "Good outdoor, easy to care plant",
    image: "/products/rubber.png",
    tags: ["outdoor"],
  },
  {
    name: "Fiddle-Leaf",
    price: 500,
    summary: "Most popular plant",
    image: "/products/fiddleLeaf.png",
    tags: ["indoor/outdoor"],
  },
  {
    name: "Sago Palm",
    price: 350,
    summary: "Loves being in sun",
    image: "/products/palm.png",
    tags: ["outdoor"],
  },
  {
    name: "Olive Bush",
    price: 400,
    summary: "Great outdoor plant and easy to care",
    image: "/products/olive.png",
    tags: ["outdoor"],
  },
  {
    name: "Parlor Palm",
    price: 120,
    summary: "Single truck palm for indoors",
    image: "/products/parlor.png",
    tags: ["indoor"],
  },
  {
    name: "Little Hope",
    price: 230,
    summary: "Dwarf version of popular Philodendron plant",
    image: "/products/hope.png",
    tags: ["indoor"],
  },
  {
    name: "Pony tail Palm",
    price: 900,
    summary: "Leaves can get upto 3feet long",
    image: "/products/pony.png",
    tags: ["indoor/outdoor"],
  },
  {
    name: "Snake Plant",
    price: 200,
    summary: "Best air purifier plant",
    image: "/products/sake.png",
    tags: ["indoor/outdoor"],
  },
  {
    name: "Kentia Palm",
    price: 550,
    summary: "Elegant, air-purifying and resiliant",
    image: "/products/kentia.png",
    tags: ["indoor"],
  },
  {
    name: "Dracenea Compacta",
    price: 200,
    summary: "an elegant, slim, low maintainance",
    image: "/products/compactka.png",
    tags: ["indoor"],
  },
  {
    name: "Ficus Audrey Tree",
    price: 450,
    summary: "Easy to care, good for indoors and outdoors",
    image: "/products/ficus.png",
    tags: ["indoor/outdoor"],
  },
  {
    name: "Monstera Deliciosa",
    price: 150,
    summary: "One of the best indoors",
    image: "/products/montrea.png",
    tags: ["indoor"],
  },
  {
    name: "pink rubber tree",
    price: 400,
    summary: "A variety of varigated rubber tree",
    image: "/products/pink.png",
    tags: ["outdoor"],
  },
  {
    name: "Jade Pothos",
    price: 100,
    summary: "Good indoor plant",
    image: "/products/jade.png",
    tags: ["indoor"],
  },
];
export default Plants;
